name: OSX
on:
  push:


jobs:
  xcode-debug:
    name: OSX Debug
    runs-on: macos-13-xlarge

    env:
      TREAT_WARNINGS_AS_ERRORS: 1

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: ${{ inputs.git_ref }}

    - name: Docker
      shell: bash
      run: |
        brew install docker colima
        docker --version
        colima start
        docker ps


    - name: Print Logs
      if: always()
      shell: bash
      run: |
        cat /Users/runner/.colima/_lima/colima/*.log
