name: OSX
on:
  push:


jobs:
  xcode-debug:
    name: OSX Debug
    runs-on: macos-14

    env:
      TREAT_WARNINGS_AS_ERRORS: 1

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: ${{ inputs.git_ref }}

    - name: Docker
      shell: bash
      run: |
        brew install docker wget colima
        docker --version
        # wget --quiet https://desktop.docker.com/mac/main/arm64/Docker.dmg
        # sudo hdiutil attach Docker.dmg
        # sudo /Volumes/Docker/Docker.app/Contents/MacOS/install
        # sudo hdiutil detach /Volumes/Docker
        # open -a Docker
        # sleep 20
        colima start --disk 10 --vm-type=vz --cpu 2 --memory 2 --runtime containerd
        docker ps


    - name: Print Logs
      if: always()
      shell: bash
      run: |
        cat /Users/runner/.colima/_lima/colima/serial*.log
